### ISSUE TITLE
I2S Method from Neopixels should be switched to RMT

### ISSUE THREAD

**Issue by martinberlin** [IoTPanic/pixels#4]
Hello Samuel,
I experienced this yesterday with one of my father projects, could never reproduce it on my stripes, but anyways we should switch to RMT since the Neopixels library owner also recommends it:
https://github.com/Makuna/NeoPixelBus/issues/292

It's a very easy change in src/pixels.cpp :
```c
#ifdef RGBW
    NeoPixelBus<NeoRgbwFeature, NeoEsp32Rmt0Ws2812xMethod> strip(PIXELCOUNT, PIXELPIN);
#else
    // RGB 3 bytes * pixel
    NeoPixelBus<NeoGrbFeature, NeoEsp32Rmt0Ws2812xMethod> strip(PIXELCOUNT, PIXELPIN);
#endif
```

I would also take the change to clean up and leave only this simple if ...else, and with your authorization remove the huge // Pixels Ascii Art since it gives a warning while compiling.

Shall I make a pull request and pass it to you?

**Comment by IoTPanic** [comment]
Yeah, go ahead and make a pull request.

**Comment by martinberlin** [comment]
Done, you will have to merge it, since I don't have write access

**Comment by martinberlin** [comment]
Merged and already using RMT channels for this
