### ISSUE TITLE
Add a new header byte to recognize PIX565 and read the colors using 2 bytes

### ISSUE THREAD

**Issue by martinberlin** [IoTPanic/pixels#7]
Since I started testing with bigger Matrixes, like 50*20, I realized even with compression is always on the limit and skips frames all the time.
So I would like to try to implement 565:

5 bits for Red
6 for Green 
5 for Blue

That will reduce the load (And the color combinations) to 1/3 (2000 bytes for 1000 RGB instead of 3K)
Spectre did it already in his protocol here: 
https://github.com/spectrenoir06/OctoWifi-LEDs-Controller/blob/master/src/main.cpp#L282

I'm currently using bytes 2 & 3 to send chunk size. So I would like to expand header bytes to 6 and add last byte as "type":
0 would be 1 byte per color like now
1 would be 565 RGB

Tell me if you have time if not I will try to cope with this. 
Samuel the branch I'm using now is: https://github.com/IoTPanic/pixels/compare/master...martinberlin:feature/3-chunks
I didn't make a pull request for this since was a personal experiment, but I think works pretty good, and still will work disabling the chunks. If you have some minutes please review my updates.

**Comment by martinberlin** [comment]
Implemented and documented here:
 https://github.com/martinberlin/pixels

I would like to have one header byte more, since I need to send chunksize, so we can update different panels in chunks (For example, I update 1000 pixels, using Gpio19 for first matrix and Gpio18 for the next one)
But it's just a personal take to make things faster. I don't know if you would like the update, I think what is cool from an open source library is precisely that you can fork it and make it your own :)

**Comment by IoTPanic** [comment]
Wow this is an old issue, my bad, new version of PIXELs just generically encodes array data, so you can just set it up as two bytes, but are you still interested in having some code in the library that would decode PIX565 data?

**Comment by martinberlin** [comment]
No this just got too old. Let’s see when I find some time to make a new update of udpx
